// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bootrlm_cpp
Rcpp::List bootrlm_cpp(arma::vec y, arma::mat x, arma::umat rep, int method, Rcpp::List options);
RcppExport SEXP bootrlm_bootrlm_cpp(SEXP ySEXP, SEXP xSEXP, SEXP repSEXP, SEXP methodSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type rep(repSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    __result = Rcpp::wrap(bootrlm_cpp(y, x, rep, method, options));
    return __result;
END_RCPP
}
