# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib bootrlm
#' @importFrom Rcpp sourceCpp
NULL

bootrlm_cpp <- function(y, x, rep, method, options) {
    .Call('bootrlm_bootrlm_cpp', PACKAGE = 'bootrlm', y, x, rep, method, options)
}

